<?php
echo '
';
?>
<!DOCTYPE >
<html>
    <head>
        <meta charset="UTF-8">
        <link href="seven_mmi.css" rel="stylesheet">
    </head>
    <body>
        <h1>Seven MMI</h1>
        <p>Trouvez les 7 différences dans l\'image de droite !</p>
        <section id="section01">
            <div id="image01">
                <img id="img1" src="img/Image01.jpg" alt="Image de référence">
            </div>
            <div id="image02">
                <img id="img2" src="img/Image02.jpg" alt="Image avec les différences">
            </div>
        </section>
        <section id="teste">
            <div id="conteneur_timer">
                <p id="timer"></p>
            </div>
            <!-- Image Map Generated by http://www.image-map.net/ -->
            <img src="img/Image01.jpg" usemap="#image-map">

            <map name="image-map">
                <area id="erreur1" target="" alt="" title=""  coords="429,256,443,243,472,240,483,266,480,282,454,286,431,279" shape="poly">
                <area id="erreur2" target="" alt="" title=""  coords="36,227,141,226,138,275,26,281" shape="poly">
                <area id="erreur3" target="" alt="" title=""  coords="476,371,384,354,291,365,385,393" shape="poly">
                <area id="erreur4" target="" alt="" title=""  coords="438,150,557,249,589,99,580,56,535,63" shape="poly">

            </map>
            <div id="erreur_trouver">

            </div>
        </section>
        <h2>Différences trouvées : VALEUR JAVASCRIPT </h2>
    </body>
     <script type="text/javascript" src="seven_mmi.js"></script>
</html>
